export type CategoryId = 'zomer' | 'verwarming' | 'gadgets' | 'sfeer' | 'gezin' | 'wellness'

export const CATEGORIES: { id: CategoryId; emoji: string }[] = [
  { id: 'zomer', emoji: '🌊' },
  { id: 'verwarming', emoji: '🧣' },
  { id: 'gadgets', emoji: '🎧' },
  { id: 'sfeer', emoji: '💡' },
  { id: 'gezin', emoji: '⛺' },
  { id: 'wellness', emoji: '🧖' },
]

const MAP: Record<string, CategoryId> = {
  'draagbare-campingventilator-20000mah-met-led-lamp': 'zomer',
  'draagbare-luchtkoeler-6l-verdampend': 'zomer',
  'draagbare-nekventilator-8000mah-bladloos': 'zomer',
  'pcm-koelhalsband-herbruikbaar': 'zomer',
  'coolify-3-nek-airconditioner': 'zomer',
  '3-in-1-mistkoelventilator': 'zomer',
  'gobi-heat-breeze-koelvest': 'zomer',
  'dreo-turbocool-misting-fan': 'zomer',
  'draagbare-usb-blender-700ml': 'gadgets',
  'led-lamp-draadloos-opladen': 'gadgets',
  'slimme-houdingscorrecter': 'wellness',
  'opvouwbare-laptopstandaard': 'gadgets',
  'magnetische-kabelclips': 'gadgets',
  'elektrische-deken-180x130cm-met-timer': 'verwarming',
  'magnetische-handwarmer-2-in-1': 'verwarming',
  'verwarmde-sokken-met-5000mah-batterij': 'verwarming',
  'warmtekruik-met-zachte-pluche-hoes': 'verwarming',
  'essager-powerbank-65w': 'gadgets',
  'kz-edx-pro-x': 'gadgets',
  'laxasfit-h9-pro-max': 'gadgets',
  'magcubic-hy300-pro': 'gadgets',
  'magsafe-3in1': 'gadgets',
  'noodradio-lototg': 'gadgets',
  'usb-c-240w-kabel': 'gadgets',
  'led-strip-app': 'sfeer',
  'star-projector': 'sfeer',
  'opblaasbaar-familiezwembad-verdikt-pvc': 'gezin',
  'spin-scrubber': 'wellness',
  'hoofdmassageborstel-haargroei': 'wellness',
  'dieren-verzorgingshandschoen': 'gezin',
  'hondendraagtas-dubbelschouder': 'gezin',
  'hondendraagtas-rugzak': 'gezin',
  'huisdier-autostoel-hond': 'gezin',
  'zwangerschapskussen-u-vorm': 'wellness',
  'zwangerschaps-buikband': 'wellness',
  'postpartum-buikband': 'wellness',
  'houten-dier-puzzel-montessori': 'gadgets',
  'montessori-drukbord-schakelaars': 'gadgets',
  'houten-klok-leertijd': 'gadgets',
  'montessori-wiskunde-cijferkaart': 'gadgets',
  'kinderen-kleuren-sorteer-speelgoed': 'gadgets',
  'ems-pols-massager': 'wellness',
  '3-in-1-rugmassager-warmte': 'wellness',
  'u-vorm-nekmassager': 'wellness',
  'oogmassager-airbag': 'wellness',
  'pulsoximeter-vinger': 'wellness',
  'gua-sha-massage-set': 'wellness',
  'acupressuurmat-yoga': 'wellness',
  'rhino-rescue-trauma-kit': 'wellness',
  'rhino-rescue-ehbo-navul': 'wellness',
  'overlevingsdeken-mylar': 'gezin',
  'zonnepaneel-powerbank-20000': 'gadgets',
  'waterfilter-persoonlijk': 'wellness',
  'multitool-18-in-1': 'gadgets',
  'noodfluitje-overleving': 'gadgets',
  'aansteker-noodweerbestendig': 'gadgets',
  'noodkaarsen-set-12': 'gezin',
  'noodpakket-72-uur-compleet': 'wellness',
  'walkie-talkie-set-2': 'gadgets',
  'rookgranaat-noodsignaal': 'gezin',
  'bushcraft-overlevingsmes': 'gadgets',
  'firestarter-set-outdoor': 'gadgets',
  'paracord-armband-overleving': 'gadgets',
  'survival-kompas-militair': 'gadgets',
  'noodtent-bivakzak': 'gezin',
  'ehbo-kit-compact-60': 'wellness',
  'overlevingsbijl-kamp': 'gadgets',
}

export function productCategory(id: string): CategoryId | null {
  return MAP[id] ?? null
}